version: "3.9"

services:
  client:
    build:
      context: ../
      dockerfile: Dockerfile
      target: final
    image: ${IMAGE_BASE_NAME}-go:latest
    container_name: ${BASE_NAME}-client
    volumes:
      - "../config.json:/opt/app/config.json"
    entrypoint: "/entrypoint.sh"
    command: --config=config.json --module=client

networks:
  default:
    name: ${NETWORK}
